@host = http://localhost:8900
@token1 = 8IuEzCmgZyNg5Wu1UPVUt32GuDMXPi0q
@token2 = fQbzONJAAw
### Public Pages
GET {{host}}/public/1.md
###
# Token Test
POST {{host}}/token  HTTP/ 1.1
Content-Type: application/json

{
    "token": "8IuEzCmgZyNg5Wu1UPVUt32GuDMXPi0q"
}

################################
### Ob Today Get
GET {{host}}/ob/today HTTP/ 1.1
Token:  {{token1}}
### Ob Today Post
POST  {{host}}/ob/today HTTP/ 1.1
Token:  {{token1}}
Content-Type: application/json

{"content":" New From Test"}
### Ob TodayAll Post
POST {{host}}/ob/today/all HTTP/ 1.1
Token:  {{token1}}
Content-Type: application/json

{"content":" All Str\n"}
### Ob 3 Days Get
OPTIONS  {{host}}/ob/recent HTTP/ 1.1
###
GET {{host}}/ob/recent HTTP/ 1.1
Token:  {{token1}}

### 
POST {{host}}/ob/general
Token: {{token2}}
Content-Type: application/json

{"content":"test From general"}
### flomo like
POST {{host}}/ob/general/{{token2}}
Content-Type: application/json

{"content":"test From general"}
################################
### 简易的剪裁 web 网页
POST  {{host}}/ob/url HTTP/ 1.1
Token:  {{token2}}
Content-Type: application/json

{"url":"https://www.ftls.xyz/posts/anki-sync-server-rs-docker/"}

###
GET {{host}}/404
###
GET {{host}}/info

###
GET {{host}}/ HTTP/ 1.1
###
GET {{host}}/time HTTP/ 1.1
### emailSendToken
GET {{host}}/api/sendtoken2mail HTTP/ 1.1