@host = http://localhost:8900
@token1 = NOSvVEL02BoxOCu6VQI4BHiFP38ZveE2
@token2 = fQbzONJAAw
# emailSendToken
GET {{host}}/api/sendtoken2mail HTTP/ 1.1
###
# Token Test
POST {{host}}/token  HTTP/ 1.1
Content-Type: application/json

{
    "token": "NOSvVEL02BoxOCu6VQI4BHiFP38ZveE2"
}
###
GET {{host}}/ HTTP/ 1.1
###
GET {{host}}/time HTTP/ 1.1
###
GET {{host}}/ob/today HTTP/ 1.1
Token:  {{token1}}
###
GET {{host}}/ob/recent HTTP/ 1.1
Token:  {{token1}}
###
POST  {{host}}/ob/url HTTP/ 1.1
Token:  {{token2}}
Content-Type: application/json

{"url":"https://www.jianshu.com/p/bb11a55dc84d"}

###
GET {{host}}/404

###
GET {{host}}/test