@host = http://localhost:8900
# emailSendToken
GET {{host}}/api/sendtoken2mail HTTP/ 1.1
###
# Token Test
POST {{host}}/token  HTTP/ 1.1
Content-Type: application/json

{
    "token": "g8BVPFLWeY9qiwF2oOVxM5QPMen1xVHT"
}
###
GET {{host}}/index.html HTTP/ 1.1
###
GET {{host}}/time HTTP/ 1.1
###
GET {{host}}/ob/today HTTP/ 1.1
Token:  NOSvVEL02BoxOCu6VQI4BHiFP38ZveE2
