@host = http://localhost:3015/ob
#@host = https://api.ftls.xyz/ob
@token = yourtoken
###
GET {{host}}/ob/today
Token: {{token}}
###
{{host}}/recent
Token: {{token}}
###
GET {{host}}/today
Token: {{token}}
Content-Type: application/json


###
POST  {{host}}/today
Token: {{token}}
Content-Type: application/json

{"content":"hello"}
